#[derive(Debug, Clone, Copy)]
pub struct NewsSourcePreset {
    pub id: &'static str,
    pub display_label: &'static str,
    pub name: &'static str,
    pub stream_url: &'static str,
    pub ticker_url: Option<&'static str>,
    pub is_live_video: bool,
    pub notes: &'static str,
}

const BUILTIN_NEWS_SOURCES: &[NewsSourcePreset] = &[
    NewsSourcePreset {
        id: "euronews",
        display_label: "Europe / Pan-European: Euronews Live",
        name: "Euronews",
        stream_url: "https://www.youtube.com/watch?v=pykpO5kQJ98",
        ticker_url: Some("https://www.euronews.com/rss"),
        is_live_video: true,
        notes: "Pan-European live news channel with official RSS headlines.",
    },
    NewsSourcePreset {
        id: "aljazeera",
        display_label: "Middle East / Qatar: Al Jazeera English Live",
        name: "Al Jazeera English",
        stream_url: "https://www.youtube.com/watch?v=gCNeDWCI0vo",
        ticker_url: Some("https://www.aljazeera.com/xml/rss/all.xml"),
        is_live_video: true,
        notes: "Global live channel with broad world coverage and RSS output.",
    },
    NewsSourcePreset {
        id: "france24",
        display_label: "Europe / France: France 24 English Live",
        name: "France 24",
        stream_url: "https://www.youtube.com/watch?v=l8PMl7tUDIE",
        ticker_url: Some("https://www.france24.com/en/rss"),
        is_live_video: true,
        notes: "English live channel backed by official France 24 RSS.",
    },
    NewsSourcePreset {
        id: "dw",
        display_label: "Europe / Germany: DW News Live",
        name: "DW News",
        stream_url: "https://www.youtube.com/watch?v=GE_SfNVNyqk",
        ticker_url: Some("https://rss.dw.com/rdf/rss-en-all"),
        is_live_video: true,
        notes: "Deutsche Welle live stream with English RSS headlines.",
    },
    NewsSourcePreset {
        id: "yahoo_finance",
        display_label: "Markets / Global: Yahoo Finance Live",
        name: "Yahoo Finance",
        stream_url: "https://www.youtube.com/watch?v=9Auq9mYxFEE",
        ticker_url: Some("https://finance.yahoo.com/news/rssindex"),
        is_live_video: true,
        notes: "Financial live channel plus official Yahoo Finance RSS.",
    },
    NewsSourcePreset {
        id: "bloomberg_tv",
        display_label: "Markets / Global: Bloomberg TV Live",
        name: "Bloomberg TV",
        stream_url: "https://www.youtube.com/watch?v=dp8PhLsUcFE",
        ticker_url: Some("https://feeds.bloomberg.com/markets/news.rss"),
        is_live_video: true,
        notes: "Global business live video paired with Bloomberg markets RSS.",
    },
    NewsSourcePreset {
        id: "nasa_tv",
        display_label: "Science / USA: NASA TV Live",
        name: "NASA TV",
        stream_url: "https://www.youtube.com/watch?v=21X5lGlDOfg",
        ticker_url: Some("https://www.nasa.gov/rss/dyn/breaking_news.rss"),
        is_live_video: true,
        notes: "Science/live mission coverage with NASA breaking-news RSS.",
    },
    NewsSourcePreset {
        id: "bbc_world",
        display_label: "Europe / United Kingdom: BBC News World Feed",
        name: "BBC News World",
        stream_url: "https://feeds.bbci.co.uk/news/world/rss.xml",
        ticker_url: Some("https://feeds.bbci.co.uk/news/world/rss.xml"),
        is_live_video: false,
        notes: "Official BBC world RSS feed.",
    },
    NewsSourcePreset {
        id: "npr_top",
        display_label: "North America / USA: NPR Top Stories Feed",
        name: "NPR Top Stories",
        stream_url: "https://feeds.npr.org/1001/rss.xml",
        ticker_url: Some("https://feeds.npr.org/1001/rss.xml"),
        is_live_video: false,
        notes: "Official NPR top stories RSS feed.",
    },
    NewsSourcePreset {
        id: "techcrunch",
        display_label: "Technology / USA: TechCrunch Feed",
        name: "TechCrunch",
        stream_url: "https://techcrunch.com/feed/",
        ticker_url: Some("https://techcrunch.com/feed/"),
        is_live_video: false,
        notes: "Technology RSS feed.",
    },
    NewsSourcePreset {
        id: "theverge",
        display_label: "Technology / USA: The Verge Feed",
        name: "The Verge",
        stream_url: "https://www.theverge.com/rss/index.xml",
        ticker_url: Some("https://www.theverge.com/rss/index.xml"),
        is_live_video: false,
        notes: "Technology RSS feed.",
    },
    NewsSourcePreset {
        id: "documentary_heaven",
        display_label: "Documentary / Global: DocumentaryHeaven Feed",
        name: "DocumentaryHeaven",
        stream_url: "https://documentaryheaven.com/feed/",
        ticker_url: Some("https://documentaryheaven.com/feed/"),
        is_live_video: false,
        notes: "Documentary site feed, useful for slow-moving headline rotation.",
    },
    NewsSourcePreset {
        id: "google_world_en",
        display_label: "Global / World: Google News Top Stories",
        name: "Google News World",
        stream_url: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en"),
        is_live_video: false,
        notes: "Worldwide Google News top stories feed.",
    },
    NewsSourcePreset {
        id: "google_us_en",
        display_label: "North America / USA: Google News Top Stories",
        name: "Google News USA",
        stream_url: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en"),
        is_live_video: false,
        notes: "US-localized Google News top stories.",
    },
    NewsSourcePreset {
        id: "google_ca_en",
        display_label: "North America / Canada: Google News Top Stories",
        name: "Google News Canada",
        stream_url: "https://news.google.com/rss?hl=en-CA&gl=CA&ceid=CA:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-CA&gl=CA&ceid=CA:en"),
        is_live_video: false,
        notes: "Canada-localized Google News top stories.",
    },
    NewsSourcePreset {
        id: "google_mx_es",
        display_label: "Latin America / Mexico: Google News Top Stories",
        name: "Google News Mexico",
        stream_url: "https://news.google.com/rss?hl=es-419&gl=MX&ceid=MX:es-419",
        ticker_url: Some("https://news.google.com/rss?hl=es-419&gl=MX&ceid=MX:es-419"),
        is_live_video: false,
        notes: "Mexico-localized Google News feed in Spanish.",
    },
    NewsSourcePreset {
        id: "google_br_pt",
        display_label: "Latin America / Brazil: Google News Top Stories",
        name: "Google News Brazil",
        stream_url: "https://news.google.com/rss?hl=pt-BR&gl=BR&ceid=BR:pt-419",
        ticker_url: Some("https://news.google.com/rss?hl=pt-BR&gl=BR&ceid=BR:pt-419"),
        is_live_video: false,
        notes: "Brazil-localized Google News feed in Portuguese.",
    },
    NewsSourcePreset {
        id: "google_ar_es",
        display_label: "Latin America / Argentina: Google News Top Stories",
        name: "Google News Argentina",
        stream_url: "https://news.google.com/rss?hl=es-419&gl=AR&ceid=AR:es-419",
        ticker_url: Some("https://news.google.com/rss?hl=es-419&gl=AR&ceid=AR:es-419"),
        is_live_video: false,
        notes: "Argentina-localized Google News feed in Spanish.",
    },
    NewsSourcePreset {
        id: "google_co_es",
        display_label: "Latin America / Colombia: Google News Top Stories",
        name: "Google News Colombia",
        stream_url: "https://news.google.com/rss?hl=es-419&gl=CO&ceid=CO:es-419",
        ticker_url: Some("https://news.google.com/rss?hl=es-419&gl=CO&ceid=CO:es-419"),
        is_live_video: false,
        notes: "Colombia-localized Google News feed in Spanish.",
    },
    NewsSourcePreset {
        id: "google_uk_en",
        display_label: "Europe / United Kingdom: Google News Top Stories",
        name: "Google News UK",
        stream_url: "https://news.google.com/rss?hl=en-GB&gl=GB&ceid=GB:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-GB&gl=GB&ceid=GB:en"),
        is_live_video: false,
        notes: "UK-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_de_de",
        display_label: "Europe / Germany: Google News Top Stories",
        name: "Google News Germany",
        stream_url: "https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de",
        ticker_url: Some("https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de"),
        is_live_video: false,
        notes: "Germany-localized Google News feed in German.",
    },
    NewsSourcePreset {
        id: "google_fr_fr",
        display_label: "Europe / France: Google News Top Stories",
        name: "Google News France",
        stream_url: "https://news.google.com/rss?hl=fr&gl=FR&ceid=FR:fr",
        ticker_url: Some("https://news.google.com/rss?hl=fr&gl=FR&ceid=FR:fr"),
        is_live_video: false,
        notes: "France-localized Google News feed in French.",
    },
    NewsSourcePreset {
        id: "google_es_es",
        display_label: "Europe / Spain: Google News Top Stories",
        name: "Google News Spain",
        stream_url: "https://news.google.com/rss?hl=es&gl=ES&ceid=ES:es",
        ticker_url: Some("https://news.google.com/rss?hl=es&gl=ES&ceid=ES:es"),
        is_live_video: false,
        notes: "Spain-localized Google News feed in Spanish.",
    },
    NewsSourcePreset {
        id: "google_it_it",
        display_label: "Europe / Italy: Google News Top Stories",
        name: "Google News Italy",
        stream_url: "https://news.google.com/rss?hl=it&gl=IT&ceid=IT:it",
        ticker_url: Some("https://news.google.com/rss?hl=it&gl=IT&ceid=IT:it"),
        is_live_video: false,
        notes: "Italy-localized Google News feed in Italian.",
    },
    NewsSourcePreset {
        id: "google_nl_nl",
        display_label: "Europe / Netherlands: Google News Top Stories",
        name: "Google News Netherlands",
        stream_url: "https://news.google.com/rss?hl=nl&gl=NL&ceid=NL:nl",
        ticker_url: Some("https://news.google.com/rss?hl=nl&gl=NL&ceid=NL:nl"),
        is_live_video: false,
        notes: "Netherlands-localized Google News feed in Dutch.",
    },
    NewsSourcePreset {
        id: "google_se_sv",
        display_label: "Europe / Sweden: Google News Top Stories",
        name: "Google News Sweden",
        stream_url: "https://news.google.com/rss?hl=sv&gl=SE&ceid=SE:sv",
        ticker_url: Some("https://news.google.com/rss?hl=sv&gl=SE&ceid=SE:sv"),
        is_live_video: false,
        notes: "Sweden-localized Google News feed in Swedish.",
    },
    NewsSourcePreset {
        id: "google_pl_pl",
        display_label: "Europe / Poland: Google News Top Stories",
        name: "Google News Poland",
        stream_url: "https://news.google.com/rss?hl=pl&gl=PL&ceid=PL:pl",
        ticker_url: Some("https://news.google.com/rss?hl=pl&gl=PL&ceid=PL:pl"),
        is_live_video: false,
        notes: "Poland-localized Google News feed in Polish.",
    },
    NewsSourcePreset {
        id: "google_gr_el",
        display_label: "Europe / Greece: Google News Top Stories",
        name: "Google News Greece",
        stream_url: "https://news.google.com/rss?hl=el&gl=GR&ceid=GR:el",
        ticker_url: Some("https://news.google.com/rss?hl=el&gl=GR&ceid=GR:el"),
        is_live_video: false,
        notes: "Greece-localized Google News feed in Greek.",
    },
    NewsSourcePreset {
        id: "google_rs_sr",
        display_label: "Europe / Serbia: Google News Top Stories",
        name: "Google News Serbia",
        stream_url: "https://news.google.com/rss?hl=sr&gl=RS&ceid=RS:sr",
        ticker_url: Some("https://news.google.com/rss?hl=sr&gl=RS&ceid=RS:sr"),
        is_live_video: false,
        notes: "Serbia-localized Google News feed in Serbian.",
    },
    NewsSourcePreset {
        id: "google_hr_hr",
        display_label: "Europe / Croatia: Google News Top Stories",
        name: "Google News Croatia",
        stream_url: "https://news.google.com/rss?hl=hr&gl=HR&ceid=HR:hr",
        ticker_url: Some("https://news.google.com/rss?hl=hr&gl=HR&ceid=HR:hr"),
        is_live_video: false,
        notes: "Croatia-localized Google News feed in Croatian.",
    },
    NewsSourcePreset {
        id: "google_ua_uk",
        display_label: "Europe / Ukraine: Google News Top Stories",
        name: "Google News Ukraine",
        stream_url: "https://news.google.com/rss?hl=uk&gl=UA&ceid=UA:uk",
        ticker_url: Some("https://news.google.com/rss?hl=uk&gl=UA&ceid=UA:uk"),
        is_live_video: false,
        notes: "Ukraine-localized Google News feed in Ukrainian.",
    },
    NewsSourcePreset {
        id: "google_tr_tr",
        display_label: "Europe / Turkey: Google News Top Stories",
        name: "Google News Turkey",
        stream_url: "https://news.google.com/rss?hl=tr&gl=TR&ceid=TR:tr",
        ticker_url: Some("https://news.google.com/rss?hl=tr&gl=TR&ceid=TR:tr"),
        is_live_video: false,
        notes: "Turkey-localized Google News feed in Turkish.",
    },
    NewsSourcePreset {
        id: "google_il_he",
        display_label: "Middle East / Israel: Google News Top Stories",
        name: "Google News Israel",
        stream_url: "https://news.google.com/rss?hl=he&gl=IL&ceid=IL:he",
        ticker_url: Some("https://news.google.com/rss?hl=he&gl=IL&ceid=IL:he"),
        is_live_video: false,
        notes: "Israel-localized Google News feed in Hebrew.",
    },
    NewsSourcePreset {
        id: "google_ae_ar",
        display_label: "Middle East / United Arab Emirates: Google News Top Stories",
        name: "Google News UAE",
        stream_url: "https://news.google.com/rss?hl=ar&gl=AE&ceid=AE:ar",
        ticker_url: Some("https://news.google.com/rss?hl=ar&gl=AE&ceid=AE:ar"),
        is_live_video: false,
        notes: "UAE-localized Google News feed in Arabic.",
    },
    NewsSourcePreset {
        id: "google_eg_ar",
        display_label: "Middle East / Egypt: Google News Top Stories",
        name: "Google News Egypt",
        stream_url: "https://news.google.com/rss?hl=ar&gl=EG&ceid=EG:ar",
        ticker_url: Some("https://news.google.com/rss?hl=ar&gl=EG&ceid=EG:ar"),
        is_live_video: false,
        notes: "Egypt-localized Google News feed in Arabic.",
    },
    NewsSourcePreset {
        id: "google_za_en",
        display_label: "Africa / South Africa: Google News Top Stories",
        name: "Google News South Africa",
        stream_url: "https://news.google.com/rss?hl=en-ZA&gl=ZA&ceid=ZA:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-ZA&gl=ZA&ceid=ZA:en"),
        is_live_video: false,
        notes: "South Africa-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_ng_en",
        display_label: "Africa / Nigeria: Google News Top Stories",
        name: "Google News Nigeria",
        stream_url: "https://news.google.com/rss?hl=en-NG&gl=NG&ceid=NG:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-NG&gl=NG&ceid=NG:en"),
        is_live_video: false,
        notes: "Nigeria-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_ke_en",
        display_label: "Africa / Kenya: Google News Top Stories",
        name: "Google News Kenya",
        stream_url: "https://news.google.com/rss?hl=en-KE&gl=KE&ceid=KE:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-KE&gl=KE&ceid=KE:en"),
        is_live_video: false,
        notes: "Kenya-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_in_en",
        display_label: "Asia / India: Google News Top Stories",
        name: "Google News India",
        stream_url: "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"),
        is_live_video: false,
        notes: "India-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_jp_ja",
        display_label: "Asia / Japan: Google News Top Stories",
        name: "Google News Japan",
        stream_url: "https://news.google.com/rss?hl=ja&gl=JP&ceid=JP:ja",
        ticker_url: Some("https://news.google.com/rss?hl=ja&gl=JP&ceid=JP:ja"),
        is_live_video: false,
        notes: "Japan-localized Google News feed in Japanese.",
    },
    NewsSourcePreset {
        id: "google_kr_ko",
        display_label: "Asia / South Korea: Google News Top Stories",
        name: "Google News South Korea",
        stream_url: "https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko",
        ticker_url: Some("https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko"),
        is_live_video: false,
        notes: "South Korea-localized Google News feed in Korean.",
    },
    NewsSourcePreset {
        id: "google_sg_en",
        display_label: "Asia / Singapore: Google News Top Stories",
        name: "Google News Singapore",
        stream_url: "https://news.google.com/rss?hl=en-SG&gl=SG&ceid=SG:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-SG&gl=SG&ceid=SG:en"),
        is_live_video: false,
        notes: "Singapore-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_id_id",
        display_label: "Asia / Indonesia: Google News Top Stories",
        name: "Google News Indonesia",
        stream_url: "https://news.google.com/rss?hl=id&gl=ID&ceid=ID:id",
        ticker_url: Some("https://news.google.com/rss?hl=id&gl=ID&ceid=ID:id"),
        is_live_video: false,
        notes: "Indonesia-localized Google News feed in Bahasa Indonesia.",
    },
    NewsSourcePreset {
        id: "google_ph_en",
        display_label: "Asia / Philippines: Google News Top Stories",
        name: "Google News Philippines",
        stream_url: "https://news.google.com/rss?hl=en-PH&gl=PH&ceid=PH:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-PH&gl=PH&ceid=PH:en"),
        is_live_video: false,
        notes: "Philippines-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_au_en",
        display_label: "Oceania / Australia: Google News Top Stories",
        name: "Google News Australia",
        stream_url: "https://news.google.com/rss?hl=en-AU&gl=AU&ceid=AU:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-AU&gl=AU&ceid=AU:en"),
        is_live_video: false,
        notes: "Australia-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "google_nz_en",
        display_label: "Oceania / New Zealand: Google News Top Stories",
        name: "Google News New Zealand",
        stream_url: "https://news.google.com/rss?hl=en-NZ&gl=NZ&ceid=NZ:en",
        ticker_url: Some("https://news.google.com/rss?hl=en-NZ&gl=NZ&ceid=NZ:en"),
        is_live_video: false,
        notes: "New Zealand-localized Google News feed in English.",
    },
    NewsSourcePreset {
        id: "guardian_world",
        display_label: "Global / World: The Guardian World RSS",
        name: "The Guardian World",
        stream_url: "https://www.theguardian.com/world/rss",
        ticker_url: Some("https://www.theguardian.com/world/rss"),
        is_live_video: false,
        notes: "Global world-news RSS feed from The Guardian.",
    },
    NewsSourcePreset {
        id: "ars_technica",
        display_label: "Technology / Global: Ars Technica RSS",
        name: "Ars Technica",
        stream_url: "https://feeds.arstechnica.com/arstechnica/index",
        ticker_url: Some("https://feeds.arstechnica.com/arstechnica/index"),
        is_live_video: false,
        notes: "Technology news and analysis feed.",
    },
    NewsSourcePreset {
        id: "marketwatch",
        display_label: "Markets / Global: MarketWatch Top Stories RSS",
        name: "MarketWatch",
        stream_url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
        ticker_url: Some("https://feeds.content.dowjones.io/public/rss/mw_topstories"),
        is_live_video: false,
        notes: "Global markets and business headlines RSS feed.",
    },
    NewsSourcePreset {
        id: "un_news",
        display_label: "Peace & Diplomacy / Global: UN News RSS",
        name: "UN News",
        stream_url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        ticker_url: Some("https://news.un.org/feed/subscribe/en/news/all/rss.xml"),
        is_live_video: false,
        notes: "United Nations global peace, diplomacy, and humanitarian updates.",
    },
    NewsSourcePreset {
        id: "reliefweb",
        display_label: "Humanitarian / Global: ReliefWeb Updates RSS",
        name: "ReliefWeb",
        stream_url: "https://reliefweb.int/updates/rss.xml",
        ticker_url: Some("https://reliefweb.int/updates/rss.xml"),
        is_live_video: false,
        notes: "Humanitarian emergencies and response updates curated by ReliefWeb.",
    },
    NewsSourcePreset {
        id: "custom",
        display_label: "Custom URL",
        name: "Custom",
        stream_url: "",
        ticker_url: None,
        is_live_video: false,
        notes: "Enter a direct RSS, HLS, RTSP, YouTube, or webpage URL manually.",
    },
];

pub fn builtin_news_sources() -> &'static [NewsSourcePreset] {
    BUILTIN_NEWS_SOURCES
}

pub fn builtin_news_source(id: &str) -> Option<&'static NewsSourcePreset> {
    BUILTIN_NEWS_SOURCES.iter().find(|source| source.id == id)
}

pub fn builtin_news_source_label(id: &str) -> &'static str {
    builtin_news_source(id)
        .map(|source| source.display_label)
        .unwrap_or("Custom URL")
}

pub fn builtin_news_source_name(id: &str) -> Option<&'static str> {
    builtin_news_source(id).map(|source| source.name)
}

pub fn builtin_news_source_stream_url(id: &str) -> Option<&'static str> {
    builtin_news_source(id).map(|source| source.stream_url)
}

pub fn builtin_news_source_ticker_url(id: &str) -> Option<&'static str> {
    builtin_news_source(id).and_then(|source| source.ticker_url)
}

pub fn builtin_news_source_is_live_video(id: &str) -> bool {
    builtin_news_source(id)
        .map(|source| source.is_live_video)
        .unwrap_or(false)
}
